# Generated by Django 3.0.4 on 2020-07-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_info',
            field=models.TextField(max_length=5000),
        ),
    ]
