# Generated by Django 3.0.4 on 2020-10-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200825_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_info',
            new_name='post_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
